//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryWPFApplication.UserServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inventory", Namespace="http://schemas.datacontract.org/2004/07/InventoryDataAssembly", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Inventory : InventoryWPFApplication.UserServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> INSTOCKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<InventoryWPFApplication.UserServiceReference.OrderItem> ORDER_ITEM_TABLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PRICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RESERVEDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPTION {
            get {
                return this.DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPTIONField, value) != true)) {
                    this.DESCRIPTIONField = value;
                    this.RaisePropertyChanged("DESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> INSTOCK {
            get {
                return this.INSTOCKField;
            }
            set {
                if ((this.INSTOCKField.Equals(value) != true)) {
                    this.INSTOCKField = value;
                    this.RaisePropertyChanged("INSTOCK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<InventoryWPFApplication.UserServiceReference.OrderItem> ORDER_ITEM_TABLE {
            get {
                return this.ORDER_ITEM_TABLEField;
            }
            set {
                if ((object.ReferenceEquals(this.ORDER_ITEM_TABLEField, value) != true)) {
                    this.ORDER_ITEM_TABLEField = value;
                    this.RaisePropertyChanged("ORDER_ITEM_TABLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PRICE {
            get {
                return this.PRICEField;
            }
            set {
                if ((this.PRICEField.Equals(value) != true)) {
                    this.PRICEField = value;
                    this.RaisePropertyChanged("PRICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RESERVED {
            get {
                return this.RESERVEDField;
            }
            set {
                if ((this.RESERVEDField.Equals(value) != true)) {
                    this.RESERVEDField = value;
                    this.RaisePropertyChanged("RESERVED");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.OrderItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.Inventory))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.OrderItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.Inventory))]
    public partial class EntityObject : InventoryWPFApplication.UserServiceReference.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InventoryWPFApplication.UserServiceReference.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InventoryWPFApplication.UserServiceReference.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderItem", Namespace="http://schemas.datacontract.org/2004/07/InventoryDataAssembly", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class OrderItem : InventoryWPFApplication.UserServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> COUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INVENTORY_FKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InventoryWPFApplication.UserServiceReference.Inventory INVENTORY_TABLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InventoryWPFApplication.UserServiceReference.EntityReferenceOfInventoryLWV6NzjB INVENTORY_TABLEReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InventoryWPFApplication.UserServiceReference.User USERS_TABLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InventoryWPFApplication.UserServiceReference.EntityReferenceOfUserLWV6NzjB USERS_TABLEReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> USER_FKField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> COUNT {
            get {
                return this.COUNTField;
            }
            set {
                if ((this.COUNTField.Equals(value) != true)) {
                    this.COUNTField = value;
                    this.RaisePropertyChanged("COUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string INVENTORY_FK {
            get {
                return this.INVENTORY_FKField;
            }
            set {
                if ((object.ReferenceEquals(this.INVENTORY_FKField, value) != true)) {
                    this.INVENTORY_FKField = value;
                    this.RaisePropertyChanged("INVENTORY_FK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InventoryWPFApplication.UserServiceReference.Inventory INVENTORY_TABLE {
            get {
                return this.INVENTORY_TABLEField;
            }
            set {
                if ((object.ReferenceEquals(this.INVENTORY_TABLEField, value) != true)) {
                    this.INVENTORY_TABLEField = value;
                    this.RaisePropertyChanged("INVENTORY_TABLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InventoryWPFApplication.UserServiceReference.EntityReferenceOfInventoryLWV6NzjB INVENTORY_TABLEReference {
            get {
                return this.INVENTORY_TABLEReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.INVENTORY_TABLEReferenceField, value) != true)) {
                    this.INVENTORY_TABLEReferenceField = value;
                    this.RaisePropertyChanged("INVENTORY_TABLEReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InventoryWPFApplication.UserServiceReference.User USERS_TABLE {
            get {
                return this.USERS_TABLEField;
            }
            set {
                if ((object.ReferenceEquals(this.USERS_TABLEField, value) != true)) {
                    this.USERS_TABLEField = value;
                    this.RaisePropertyChanged("USERS_TABLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InventoryWPFApplication.UserServiceReference.EntityReferenceOfUserLWV6NzjB USERS_TABLEReference {
            get {
                return this.USERS_TABLEReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.USERS_TABLEReferenceField, value) != true)) {
                    this.USERS_TABLEReferenceField = value;
                    this.RaisePropertyChanged("USERS_TABLEReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> USER_FK {
            get {
                return this.USER_FKField;
            }
            set {
                if ((this.USER_FKField.Equals(value) != true)) {
                    this.USER_FKField = value;
                    this.RaisePropertyChanged("USER_FK");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/InventoryDataAssembly", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class User : InventoryWPFApplication.UserServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIRST_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LAST_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<InventoryWPFApplication.UserServiceReference.OrderItem> ORDER_ITEM_TABLEField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FIRST_NAME {
            get {
                return this.FIRST_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.FIRST_NAMEField, value) != true)) {
                    this.FIRST_NAMEField = value;
                    this.RaisePropertyChanged("FIRST_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LAST_NAME {
            get {
                return this.LAST_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.LAST_NAMEField, value) != true)) {
                    this.LAST_NAMEField = value;
                    this.RaisePropertyChanged("LAST_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<InventoryWPFApplication.UserServiceReference.OrderItem> ORDER_ITEM_TABLE {
            get {
                return this.ORDER_ITEM_TABLEField;
            }
            set {
                if ((object.ReferenceEquals(this.ORDER_ITEM_TABLEField, value) != true)) {
                    this.ORDER_ITEM_TABLEField = value;
                    this.RaisePropertyChanged("ORDER_ITEM_TABLE");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<InventoryWPFApplication.UserServiceReference.EntityKeyMember> EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<InventoryWPFApplication.UserServiceReference.EntityKeyMember> EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<InventoryWPFApplication.UserServiceReference.EntityKeyMember>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.EntityReferenceOfInventoryLWV6NzjB))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.EntityReferenceOfUserLWV6NzjB))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<InventoryWPFApplication.UserServiceReference.Inventory>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.Inventory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<InventoryWPFApplication.UserServiceReference.OrderItem>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.OrderItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.User))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfInventoryLWV6NzjB", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfInventoryLWV6NzjB : InventoryWPFApplication.UserServiceReference.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.EntityReferenceOfUserLWV6NzjB))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.EntityReferenceOfInventoryLWV6NzjB))]
    public partial class EntityReference : InventoryWPFApplication.UserServiceReference.RelatedEnd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InventoryWPFApplication.UserServiceReference.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InventoryWPFApplication.UserServiceReference.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.EntityReferenceOfUserLWV6NzjB))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryWPFApplication.UserServiceReference.EntityReferenceOfInventoryLWV6NzjB))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfUserLWV6NzjB", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfUserLWV6NzjB : InventoryWPFApplication.UserServiceReference.EntityReference {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/logIn", ReplyAction="http://tempuri.org/IUserService/logInResponse")]
        InventoryWPFApplication.UserServiceReference.User logIn(string fname, string lname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/addPart", ReplyAction="http://tempuri.org/IUserService/addPartResponse")]
        bool addPart(string id, string descr, double price, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/reservePart", ReplyAction="http://tempuri.org/IUserService/reservePartResponse")]
        bool reservePart(string id, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/searchPartByDescription", ReplyAction="http://tempuri.org/IUserService/searchPartByDescriptionResponse")]
        System.Collections.Generic.List<InventoryWPFApplication.UserServiceReference.Inventory> searchPartByDescription(string descr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/getAllParts", ReplyAction="http://tempuri.org/IUserService/getAllPartsResponse")]
        System.Collections.Generic.List<InventoryWPFApplication.UserServiceReference.Inventory> getAllParts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/calculateTotal", ReplyAction="http://tempuri.org/IUserService/calculateTotalResponse")]
        double calculateTotal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/calculateReserved", ReplyAction="http://tempuri.org/IUserService/calculateReservedResponse")]
        double calculateReserved();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/calculateBalance", ReplyAction="http://tempuri.org/IUserService/calculateBalanceResponse")]
        double calculateBalance();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/findOrderItemById", ReplyAction="http://tempuri.org/IUserService/findOrderItemByIdResponse")]
        InventoryWPFApplication.UserServiceReference.OrderItem findOrderItemById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/addOrderItem", ReplyAction="http://tempuri.org/IUserService/addOrderItemResponse")]
        bool addOrderItem(Inventory inventory, User user, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/getCurrentUser", ReplyAction="http://tempuri.org/IUserService/getCurrentUserResponse")]
        InventoryWPFApplication.UserServiceReference.User getCurrentUser(string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/getShoppingCart", ReplyAction="http://tempuri.org/IUserService/getShoppingCartResponse")]
        System.Collections.Generic.List<InventoryWPFApplication.UserServiceReference.OrderItem> getShoppingCart(int currentUserId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : InventoryWPFApplication.UserServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<InventoryWPFApplication.UserServiceReference.IUserService>, InventoryWPFApplication.UserServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }

        public InventoryWPFApplication.UserServiceReference.User logIn(string fname, string lname)
        {
            return base.Channel.logIn(fname, lname);
        }
        
        public bool addPart(string id, string descr, double price, int count) {
            return base.Channel.addPart(id, descr, price, count);
        }
        
        public bool reservePart(string id, int count) {
            return base.Channel.reservePart(id, count);
        }
        
        public System.Collections.Generic.List<InventoryWPFApplication.UserServiceReference.Inventory> searchPartByDescription(string descr) {
            return base.Channel.searchPartByDescription(descr);
        }
        
        public System.Collections.Generic.List<InventoryWPFApplication.UserServiceReference.Inventory> getAllParts() {
            return base.Channel.getAllParts();
        }
        
        public double calculateTotal() {
            return base.Channel.calculateTotal();
        }
        
        public double calculateReserved() {
            return base.Channel.calculateReserved();
        }
        
        public double calculateBalance() {
            return base.Channel.calculateBalance();
        }
        
        public InventoryWPFApplication.UserServiceReference.OrderItem findOrderItemById(string id) {
            return base.Channel.findOrderItemById(id);
        }
        
        public bool addOrderItem(Inventory inventory, User user, int count) {
            return base.Channel.addOrderItem(inventory, user, count);
        }
        
        public InventoryWPFApplication.UserServiceReference.User getCurrentUser(string firstName, string lastName) {
            return base.Channel.getCurrentUser(firstName, lastName);
        }
        
        public System.Collections.Generic.List<InventoryWPFApplication.UserServiceReference.OrderItem> getShoppingCart(int currentUserId) {
            return base.Channel.getShoppingCart(currentUserId);
        }
    }
}
